=== Arabicsource/IslamSource/main.dtd
<!ELEMENT pages (page+|languages)>
<!ELEMENT languages (language+)>
<!ELEMENT language EMPTY>
<!ELEMENT page ((child|frame|edit|radio|ipaddr|static|image|email|download)*|addlist?)>
<!ELEMENT frame (edit|radio|ipaddr|static|image|email|download)*>
<!ELEMENT list (edit|radio|ipaddr|static)*>
<!ELEMENT child EMPTY>
<!ELEMENT edit EMPTY>
<!ELEMENT radio (option+)>
<!ELEMENT ipaddr EMPTY>
<!ELEMENT option EMPTY>
<!ELEMENT static EMPTY>
<!ELEMENT addlist EMPTY>
<!ELEMENT image EMPTY>
<!ELEMENT email EMPTY>
<!ELEMENT download EMPTY>
<!ATTLIST page name ID #REQUIRED>
<!ATTLIST page description CDATA #REQUIRED>
<!ATTLIST page summary CDATA #IMPLIED>
<!ATTLIST page level (normal|advanced|expert|hidden) "normal">
<!ATTLIST page icon CDATA #IMPLIED>
<!ATTLIST page usersort (true|false) "false">
<!ATTLIST child name IDREF #REQUIRED>
<!ATTLIST child mandatory (true|false) "false">
<!ATTLIST child maxinstances CDATA #IMPLIED>
<!ATTLIST child xmlvalue CDATA #IMPLIED>
<!ATTLIST frame name CDATA #REQUIRED>
<!ATTLIST frame description CDATA #REQUIRED>
<!ATTLIST list name CDATA #REQUIRED>
<!ATTLIST list description CDATA #REQUIRED>
<!ATTLIST edit name CDATA #REQUIRED>
<!ATTLIST edit description CDATA #REQUIRED>
<!ATTLIST edit level (normal|advanced|expert|hidden) "normal">
<!ATTLIST edit rows CDATA "1">
<!ATTLIST edit type (text|password|version|filename|filepath|dirpath|cmdline|dns|dnsip|dnsipsubnet|url|regkey|ininame|dialname|windname|md5|int8|uint8|int16|uint16|int32|uint32|int64|uint64|single|double) "text">
<!ATTLIST edit nummin CDATA #IMPLIED>
<!ATTLIST edit nummax CDATA #IMPLIED>
<!ATTLIST edit defaultvalue CDATA #IMPLIED>
<!ATTLIST edit pagename (true|false) "false">
<!ATTLIST edit readonly (true|false) "false">
<!ATTLIST radio name CDATA #REQUIRED>
<!ATTLIST radio description CDATA #REQUIRED>
<!ATTLIST radio level (normal|advanced|expert|hidden) "normal">
<!ATTLIST option name CDATA #REQUIRED>
<!ATTLIST option defaultvalue (true|false) "false">
<!ATTLIST option nextbelow (true|false) "false">
<!ATTLIST ipaddr name CDATA #REQUIRED>
<!ATTLIST ipaddr description CDATA #REQUIRED>
<!ATTLIST ipaddr level (normal|advanced|expert|hidden) "normal">
<!ATTLIST ipaddr rows CDATA "1">
<!ATTLIST ipaddr defaultvalue CDATA "0.0.0.0">
<!ATTLIST static name CDATA #REQUIRED>
<!ATTLIST static description CDATA #REQUIRED>
<!ATTLIST image name CDATA #REQUIRED>
<!ATTLIST image text CDATA #REQUIRED>
<!ATTLIST image source CDATA #REQUIRED>
<!ATTLIST image maxwidth CDATA #IMPLIED>
<!ATTLIST image maxheight CDATA #IMPLIED>
<!ATTLIST image usethumbonmax (true|false) "false">
<!ATTLIST download name CDATA #REQUIRED>
<!ATTLIST download text CDATA #REQUIRED>
<!ATTLIST download path CDATA #REQUIRED>
<!ATTLIST download userelativepath (true|false) "false">
<!ATTLIST email name CDATA #REQUIRED>
<!ATTLIST email useimage (true|false) "true">

=== Arabicsource/IslamSource/metadata/islamsource.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE pages [
<!ELEMENT pages (page+|languages)>
<!ELEMENT languages (language+)>
<!ELEMENT language EMPTY>
<!ELEMENT page ((child|frame|edit|date|radio|ipaddr|static|image|email|download|button)*|addlist?)>
<!ELEMENT frame (edit|radio|ipaddr|static|image|email|download)*>
<!ELEMENT list (edit|radio|ipaddr|static)*>
<!ELEMENT child EMPTY>
<!ELEMENT edit EMPTY>
<!ELEMENT date EMPTY>
<!ELEMENT radio (option+)>
<!ELEMENT ipaddr EMPTY>
<!ELEMENT option EMPTY>
<!ELEMENT static EMPTY>
<!ELEMENT addlist EMPTY>
<!ELEMENT image EMPTY>
<!ELEMENT email EMPTY>
<!ELEMENT download EMPTY>
<!ELEMENT button EMPTY>
<!ATTLIST page name ID #REQUIRED>
<!ATTLIST page description CDATA #REQUIRED>
<!ATTLIST page summary CDATA #IMPLIED>
<!ATTLIST page level (normal|advanced|expert|hidden) "normal">
<!ATTLIST page icon CDATA #IMPLIED>
<!ATTLIST page usersort (true|false) "false">
<!ATTLIST child name IDREF #REQUIRED>
<!ATTLIST child mandatory (true|false) "false">
<!ATTLIST child maxinstances CDATA #IMPLIED>
<!ATTLIST child xmlvalue CDATA #IMPLIED>
<!ATTLIST frame name CDATA #REQUIRED>
<!ATTLIST frame description CDATA #REQUIRED>
<!ATTLIST frame hasform (true|false) "false">
<!ATTLIST list name CDATA #REQUIRED>
<!ATTLIST list description CDATA #REQUIRED>
<!ATTLIST edit name CDATA #REQUIRED>
<!ATTLIST edit description CDATA #REQUIRED>
<!ATTLIST edit level (normal|advanced|expert|hidden) "normal">
<!ATTLIST edit rows CDATA "1">
<!ATTLIST edit type (text|password|version|filename|filepath|dirpath|cmdline|dns|dnsip|dnsipsubnet|url|regkey|ininame|dialname|windname|md5|int8|uint8|int16|uint16|int32|uint32|int64|uint64|single|double) "text">
<!ATTLIST edit nummin CDATA #IMPLIED>
<!ATTLIST edit nummax CDATA #IMPLIED>
<!ATTLIST edit defaultvalue CDATA #IMPLIED>
<!ATTLIST edit pagename (true|false) "false">
<!ATTLIST edit readonly (true|false) "false">
<!ATTLIST date name CDATA #REQUIRED>
<!ATTLIST date description CDATA #REQUIRED>
<!ATTLIST radio name CDATA #REQUIRED>
<!ATTLIST radio description CDATA #REQUIRED>
<!ATTLIST radio uselist (true|false) "false">
<!ATTLIST radio usecheck (true|false) "false">
<!ATTLIST radio level (normal|advanced|expert|hidden) "normal">
<!ATTLIST radio onpopulate CDATA #IMPLIED>
<!ATTLIST radio onchange CDATA #IMPLIED>
<!ATTLIST option name CDATA #REQUIRED>
<!ATTLIST option defaultvalue (true|false) "false">
<!ATTLIST option nextbelow (true|false) "false">
<!ATTLIST ipaddr name CDATA #REQUIRED>
<!ATTLIST ipaddr description CDATA #REQUIRED>
<!ATTLIST ipaddr level (normal|advanced|expert|hidden) "normal">
<!ATTLIST ipaddr rows CDATA "1">
<!ATTLIST ipaddr defaultvalue CDATA "0.0.0.0">
<!ATTLIST static name CDATA #REQUIRED>
<!ATTLIST static description CDATA #REQUIRED>
<!ATTLIST static onrender CDATA #IMPLIED>
<!ATTLIST image name CDATA #REQUIRED>
<!ATTLIST image text CDATA #REQUIRED>
<!ATTLIST image source CDATA #REQUIRED>
<!ATTLIST image maxwidth CDATA #IMPLIED>
<!ATTLIST image maxheight CDATA #IMPLIED>
<!ATTLIST image usethumbonmax (true|false) "false">
<!ATTLIST download name CDATA #REQUIRED>
<!ATTLIST download text CDATA #REQUIRED>
<!ATTLIST download path CDATA #REQUIRED>
<!ATTLIST download userelativepath (true|false) "true">
<!ATTLIST download showinline (true|false) "false">
<!ATTLIST email name CDATA #REQUIRED>
<!ATTLIST email useimage (true|false) "true">
<!ATTLIST button name CDATA #REQUIRED>
<!ATTLIST button description CDATA #REQUIRED>
<!ATTLIST button onclick CDATA #IMPLIED>
]>
<!-- <!DOCTYPE pages SYSTEM "main.dtd"> -->
<pages mainimage="islamsource.jpg" hoverimage="islamsourcehover.jpg" title="IslamSource">
	<page name="Home" description="IslamSource_Home">
		<frame name="intro" description="IslamSource_Introduction">
			<static name="welcome" description="IslamSource_Welcome"></static>
			<static name="goal" description="IslamSource_Goal"></static>
			<static name="credits" description="IslamSource_Credits"></static>
			<static name="introduction" description="IslamSource_Intro"></static>
			<email name="introductionemail" useimage="true"></email>
		</frame>
	</page>
	<page name="HijriCalendar" description="IslamSource_HijriCalendar">
		<frame name="info" description="IslamSource_Information">
			<static name="monthname" description="IslamSource_CurrentMonth" onrender="PrayerTime::GetMonthName"></static>
			<static name="calendar" description="IslamSource_GregorianCalendar" onrender="PrayerTime::GetCalendar"></static>
			<static name="hijrimonthname" description="IslamSource_CurrentMonth" onrender="PrayerTime::GetMonthName"></static>
			<static name="hijricalendar" description="IslamSource_HijriCalendar" onrender="PrayerTime::GetCalendar"></static>
			<static name="umalquramonthname" description="IslamSource_CurrentMonth" onrender="PrayerTime::GetMonthName"></static>
			<static name="umalquracalendar" description="IslamSource_UmAlQuraCalendar" onrender="PrayerTime::GetCalendar"></static>
		</frame>
	</page>
	<page name="PrayerTimes" description="IslamSource_PrayerTimes">
		<frame name="info" description="IslamSource_Information">
			<static name="qibladirection" description="IslamSource_QiblaDirectionFromTrueNorth" onrender="PrayerTime::GetQiblaDirection"></static>
			<static name="praytime" description="IslamSource_PrayerTimes" onrender="PrayerTime::GetPrayerTimes"></static>
		</frame>
	</page>
	<page name="Calculations" description="IslamSource_Calculations">
		<frame name="systemconversion" description="IslamSource_UnitConversion">
			<edit name="degrees" description="IslamSource_Degrees"></edit>
			<edit name="minutes" description="IslamSource_Minutes"></edit>
			<edit name="seconds" description="IslamSource_Seconds"></edit>
			<radio name="convunits" description="IslamSource_Units" onchange="UnitConversions::GetDegreeConversionUnitChangeJS"><option name="IslamSource_DegreeMinuteSecond" defaultvalue="true"></option><option name="IslamSource_DecimalDegree"></option><option name="IslamSource_Radians"></option></radio>
			<button name="compute" description="IslamSource_Compute" onclick="UnitConversions::GetDegreeConversionJS"></button>
			<static name="result" description=""></static>
		</frame>
		<frame name="systemconversion" description="IslamSource_UnitConversion">
			<edit name="latdegrees" description="IslamSource_Degrees"></edit>
			<edit name="latminutes" description="IslamSource_Minutes"></edit>
			<edit name="latseconds" description="IslamSource_Seconds"></edit>
			<edit name="londegrees" description="IslamSource_Degrees"></edit>
			<edit name="lonminutes" description="IslamSource_Minutes"></edit>
			<edit name="lonseconds" description="IslamSource_Seconds"></edit>
			<edit name="destlatdegrees" description="IslamSource_Degrees"></edit>
			<edit name="destlatminutes" description="IslamSource_Minutes"></edit>
			<edit name="destlatseconds" description="IslamSource_Seconds"></edit>
			<edit name="destlondegrees" description="IslamSource_Degrees"></edit>
			<edit name="destlonminutes" description="IslamSource_Minutes"></edit>
			<edit name="destlonseconds" description="IslamSource_Seconds"></edit>
			<edit name="destdist" description="IslamSource_Degrees"></edit>
			<edit name="destangle" description="IslamSource_Minutes"></edit>
			<radio name="convdistunits" description="IslamSource_Units"><option name="IslamSource_AngleDistance" defaultvalue="true"></option><option name="IslamSource_LatitudeLongitude"></option></radio>
			<button name="compute" description="IslamSource_Compute" onclick="UnitConversions::GetDegreeOffsetJS"></button>
			<static name="resultdist" description=""></static>
		</frame>
		<frame name="systemconversion" description="IslamSource_UnitConversion">
			<date name="date" description="IslamSource_Date"></date>
			<edit name="offset" description="IslamSource_Offset"></edit>
			<radio name="convdates" description="IslamSource_Units"><option name="IslamSource_Add" defaultvalue="true"></option><option name="IslamSource_Remove"></option></radio>
			<button name="compute" description="IslamSource_Compute" onclick="UnitConversions::GetDateOffsetJS"></button>
			<static name="resultdate" description=""></static>
		</frame>
		<frame name="systemconversion" description="IslamSource_UnitConversion">
			<date name="dateconv" description="IslamSource_Date"></date>
			<radio name="convcalendars" description="IslamSource_Units"><option name="IslamSource_GregorianCalendar" defaultvalue="true"></option><option name="IslamSource_HijriCalendar"></option><option name="IslamSource_UmAlQuraCalendar"></option></radio>
			<button name="compute" description="IslamSource_Compute" onclick="UnitConversions::GetDataConversionJS"></button>
			<static name="resultcal" description=""></static>
		</frame>
	</page>
	<page name="islam" description="IslamSource_IslamicInformation">
		<frame name="words" description="IslamSource_Viewer" hasform="true">
			<radio name="selection" description="IslamSource_Selection" uselist="true" defaultvalue="0" onpopulate="Arabic::GetCategories"></radio>
			<button name="selectiondisplay" description="IslamSource_Display"></button>
			<radio name="translitscheme" description="IslamSource_TransliterationScheme" uselist="true" onchange="Arabic::GetChangeTransliterationJS"><option name="IslamSource_Off" defaultvalue="true"></option><option name="IslamSource_PlainRoman"></option><option name="IslamSource_EnglishRomanized"></option><option name="IslamSource_ExtendedBuckwalter"></option></radio>
			<button name="fontsmaller" description="IslamSource_Smaller" onclick="ArabicFont::GetFontSmallerJS"></button>
			<button name="fontdefaultsize" description="IslamSource_LetterSample" onclick="ArabicFont::GetFontDefaultSizeJS"></button>
			<button name="fontbigger" description="IslamSource_Bigger" onclick="ArabicFont::GetFontBiggerJS"></button>
			<radio name="fontselection" description="IslamSource_Font" uselist="true" defaultvalue="def" onpopulate="ArabicFont::GetFontList" onchange="ArabicFont::GetChangeFontJS"></radio>
